version: "2"
config:
  slack_notify: true
  slack_channel: tkey-metadata-ci
jobs:
  build_docker:
    steps:
      - build_image:
          dockerfile: ./Dockerfile
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: app-platform
          workload: tkey-metadata
          argocd_pipeline: generic-v2
          deployment_config: dev
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-app-platform-prod
          namespace: default
          workload: tkey-metadata
          argocd_pipeline: generic-v2
          deployment_config: prod
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - dev
                - master
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - dev
                - master
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - dev
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - master
deployment_config:
  dev:
    readinessProbe:
      failureThreshold: 2
      initialDelaySeconds: 10
      periodSeconds: 2
      successThreshold: 3
      timeoutSeconds: 2
      httpGet:
        path: /
        port: 5051
        scheme: HTTP
    livenessProbe:
      failureThreshold: 2
      initialDelaySeconds: 10
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 2
      httpGet:
        path: /
        port: 5051
        scheme: HTTP
    ingress:
      hosts:
        - host: tkey-metadata.dev.tiki.services
          paths:
            - path: /
              port: "5051"
      autoTls: true
    replicaCount: 1
    volumes:
      - name: tkey-metadata
        secret:
          defaultMode: 420
          optional: false
          secretName: tkey-metadata
    volumeMounts:
      - mountPath: "/app/config/uat"
        name: tkey-metadata
    envFrom:
      - secretRef:
          name: env-tkey-metadata
  prod:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    readinessProbe:
      failureThreshold: 2
      initialDelaySeconds: 10
      periodSeconds: 2
      successThreshold: 3
      timeoutSeconds: 2
      httpGet:
        path: /
        port: 5051
        scheme: HTTP
    livenessProbe:
      failureThreshold: 2
      initialDelaySeconds: 10
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 2
      httpGet:
        path: /
        port: 5051
        scheme: HTTP
    ingress:
      hosts:
        - host: tkey-metadata.tiki.services
          paths:
            - path: /
              port: "5051"
      autoTls: true
    replicaCount: 2
    volumes:
      - name: tkey-metadata
        secret:
          defaultMode: 420
          optional: false
          secretName: tkey-metadata
    volumeMounts:
      - mountPath: "/app/config/prod"
        name: tkey-metadata
    envFrom:
      - secretRef:
          name: env-tkey-metadata
