version: '3'

x-logging: &logging
        logging:
                driver: "json-file"
                options:
                        max-file: "10"
                        max-size: "100m"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.19.0
    user: root # https://github.com/prometheus/prometheus/issues/5976
    restart: on-failure
    hostname: prometheus
    command: --storage.tsdb.retention.time=31d --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    <<: *logging
    depends_on: 
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    - mysql
  redis:
    restart: always
    image: redis
    env_file:
      - ./.env.development
    ports:
      - "6379:6379"
  mysql:
    restart: always
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    env_file:
      - ./.env.development
    ports:
      - "3306:3306"
  torus-metadata:
    restart: always
    depends_on:
      - mysql
      - ipfs
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "5051:5051/tcp"
    volumes:
      - .:/app
  ipfs:
    image: ipfs/go-ipfs
    ports: 
      - "5001:5001/tcp"