version: '3'

services:
  torus-metadata:
    restart: always
    depends_on:
      - ipfs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5051:5051/tcp"
  ipfs:
    image: ipfs/go-ipfs
    ports: 
      - "5001:5001/tcp"